name = "SnaggedNecklace"
uuid = "3cabd9b9-50c6-4550-8707-7ca5aa6f399b"
authors = ["Dmitri Iouchtchenko <diouchtc@uwaterloo.ca>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.5"
